# 沙箱配置
pay:
  alipay:
    gatewayUrl: https://openapi.alipay.com/gateway.do
    appid: 2018060560263740
    appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3UKLQKandbH9jE7vzl8zhThLCY/ijQ86TB50mQUGXZHvQm8/NN0IkHHIvId/YvSqtkgdxVBrw9TmKG93webxkPYSmQpwf54YzK1hSvdQk4pfd1Y2NuRnsiHVyX21EvHNr8459ID58+aQEYPQSlzvNdwWFYqnoD2q4n3emOXT3JCq6yqn/0GDTPRETxwGXcovu3f4vz4HODMf2P360sS4xkOVkYtdyGc+UWHjrWrGi2RrAgD9fe43fmBdobMJCPbFnj+LOkaW5njr4yEHZN7Xzd1Zw4+4sbXvT1Yke5WJVDU0mjI3hNTRjPc+juPACBerI0Jk7mIqIIidq8ggNbhhnAgMBAAECggEAVEnZcwmVN2DJ+g5633ivFfHGImfBTaDB/U0E7zAWLrxfSf46wEtmOCB0SEO1H31rgD+i+HMJqD25ZU2G8SmofBblRWVfUDQuupx1kiYCw6sE1VV6Lu4rg10DU8GZBn/4OmzU2afX07MdvX2u/FVZhBH0Ee7Z3QApvBZm96F3rKLHYm51kMNXywmjYkhuQ7l3+Zk4I1mNRMI7nAS0oBr94EGJb8Kpb5UT/eTDphPHIw1jyXMd1RzvxFq0lwhMtoPFi8vi2IiVEYyCTok6lc0DcKjRk+0NeUQiAtQsNTg3Lgpe7npko3e+OrEocA0J1luO+b9qNCcIDcW050sVTo0OIQKBgQDaBvVivKx5U/twdid2cFDYp+HxNUO35EL5Oxo4l9SYXV35Xl2Uf0cS9OormDHakFxS7CsIAv6QaIeYum7crYGeOUVqhjqNMBWRe4uhNdnh+VvTwpqzBlCVIbMZubN2EU8R095h21C6bf3hwQrhQu0RYPJVRn6tdDp5zi0OSsDiDwKBgQDXPfyG7u0fDb7uR/3FDlyCB2l031ixNL0lcycr30GhKwszPOIHi/Toq+392hI3ECNijqm8Bfb1mrlbrk6a6qckS1DjDI32YnnDK535oIhPuTwHX1dwwIdFAOKb5jgntpIQf77ho3qKn0xxHKgpqjzOsMFdVA1OPxj6ywBeymvcKQKBgBbtnGihxtGLj2moQ0YlUZs3LH+dRl3UV2a2XG+PKABN8VAEKHsxV1wa/XVQMA34GH1v8KaLChJNq9TX5ki2xmbJRw+IxieK4vnFsE1nyF4HRyzhzjr9cwP740XVTZYhA9uwGDbaRYcVghl3n5lI3H1zYIivPSsoie29TOev3NDpAoGBAI1V/K410aqkgg1BZJey2HfhmhPOXRTvhoxC0yPx08ya0R3yCpHeCxGFZB9exLs3c6TR/Q6j9AhOcwyKpr7++oXQluqgYc+51i6cQ32ZNijzf0FwD6DQK4LaE/M+9vzM25jN6W+Mw3inJbDYmmvRh2BJnI9GE/6fXC3Cgxm7XZwRAoGBAJWuUYtvAKurn3txapiOCjx/zHy1ktmRGyNvffFrJ8O3593GROSj8iJUUMBJ6+rfP3TdyXxd0xaOfAX2AvRJ83WCvxnyIuFcW50DJ+AMBsRlrT5rX8R/rgwO0xz4+zx+E/al6S8VXqEgMdYdYQE2hiuPqVcU9CeRSlrDQeJ3m+Ww
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApavHRgmmuBr44TCOQxTvSvlSehoTBKQiHRNuUtiexkvI/PQH1o9kXaTSknDDNerrYv/dXBIdO6H41kL+4leHUuO+G+Lsvah9s6sCQWXoNEU3Hp69BKqNV00Ua4PZPL+J65Un/07GtopN/YByl9UrZScSJGZSt5EWhNBJtK86l6U9fAFir7gcTJChWUZwbKifW2i7o0rl8D0V8aXVCliVD+JMAQxyaE8yJQC2ZN1a1f2UlBJrSyZsLIfgsxB64hvekgmSpq91K63N4EqD1lTYeOUY57XaYgBfogLwWA5ic6lgdN1C1PNYD7FuOdhgF2sFna2/dQ53vgkbYVotOsepXwIDAQAB
    returnUrl: http://fuzsmc.natappfree.cc/alipay/return
    notifyUrl: http://fuzsmc.natappfree.cc/alipay/notify
#    gatewayUrl: https://openapi.alipaydev.com/gateway.do
#    appid: 2016091400508498
#    appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtXKWs+trRSuCxEUvlsEeSAuLWs3B/Dh74R8223BnfzoA29aGeoycAqfKlBMcbzU2G1KayESvZKGpwBLeejSbecRYjgZsQDyEaDimQQJtGFvZVV6u4XNnvIJ72eQzEaEIQfuiorjBTLm6DQuds4R0GxftqON6QFoIZkWB9ZrZKd02cuy16dW+UqtLVGGAHcCIAkB63zUiKSNfweMddneZ7MVs3lvu3xhMnD+5us/+n2Vp4qhfmpYLcdqIW6InU4GypeoOpyUTrfUGpgdR0l924vHy/GQJZEKFaRcK3cYK+ECyKpSIoqaJJFLHbkqsliuPpMUG+rM3jiqeIAH4psAznAgMBAAECggEBAJ5jyEbbxrJzrAh7GhHX1fwUQPYSadTbrPYAfHX2cHlnrQMJtsk+nTLhEv0r+VJwZ8WpYkfMong8kcqYtL7ajcmsHqMAFhE9EWxBxj2ymWsXLabZe93sj30IG9Rq0nxcGQgDO0RqKWLGSFgK93Al2KRInKT3InkY53K+vR61ihVLmGf7+GwPtIZteBy+tuAyvcj2RlkYvjiFi3ySyZ1wA3sJIlgrGiixd6fj20XFGNE3CnAwu0BJgXXbP/S9J4C0RRa3ZXj8fX7oONhVxz2xKxn7AT4e8OWjt7J41H2LRct8Fgl9pqgz2FJYv/WfbkG8x9fGiKYYvPXoxjjrk/tkewkCgYEA8f9Lcu5JPrE9rpw9zlwhm5cOO81xLxdwL5R5/1bRP48BZGIYuqlCbVvjJVqtO8eTnLhUwH7fG8B7cmoeO9bGr9GQrtfyCqz6FtVymTBieJlfgZDVhtzyv2qKOBMIFE8jsbSBK/NHHMvykJ+XdQ1riwCeQDdXICRuYTTFwGk2OsUCgYEAt2SoN95tVmVrvKG6ATLNEtge/ozeVywA4GjltrSw/G9vqp+DkkT2pY19uROuzMazoTzKWpPho2q/qzNlv/ANbOFM2GEmKamQ7CO88JgRxMsPTvc/HxCLU/ClMJU8LcOf9LfP2KYZpPwuheKJoF4vDGj8NsbFmccJyYSdpkNEk7sCgYBJlL2FMaz1sgC2Ue19DIhvfaunRV1P20mSPgwmNmijccETm7w3LXX0OIdFeV/JGHLqqSWj7i+6iXk/ncKZoUGCfi8G6sQ+uL/GJ5qTt6GJV+ExTS+PtSjeSO/EAw1m13Vb+C16hpstx1l23f+4aJ81gbecgPct38XsKpaiXZtOnQKBgQCMsN7QRYYxwoq9YoDUzIlAzKYyeBVWYL6najHYUZR5hG/xQIBqZRem9/4cTvpJxKInrwA6LrrqaEl0aHDFp75U6h7O3PCvA5PXZK9dD/yJsZIj7U/yX/nTQokn1UUegrYiwiTkusBvrrtuINWePsLvTVc4GpObHnPmsiNTWsWwYwKBgENaeTNOCHV2km/ysXQSEIhKbtlAMQPsgWHCt/bzHlF9m18izb1LrJyjzcSsd+Zy78R+pv4G50Q27c3e/DFPz/wYxN/yHWRbyLBA8ipJbCtMtPEdS9krpmN6cChIdLGbz4CVUqOPSRzNb9lhhgPCcCNRq6DG3HBceb1Se9VnO3zk
#    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApFQKccMq+wPoWh93DcX3XYrnT7FJ3gntJA/jEwgk6Jd3iEVS2CyUCCgFVcQn8xjXT81YbZHYvoC50IBuu+A+Ey+J8VIgsBm5g9uwbOLRf66GrZjuKOlalHm5gHXjcL2gZRMBJEStOxstcO2YQriqhQzdL3EKp+HQc9u14IOVFpZdR8qq1l7CzKHn1vQo/1fUPfUrTLQqSuQTU9Ospv/QHFqOJA7DPetUQ+jnaZ082f3clr4ITw4EE8A6IWqTXcETTx5j/udCGP84g2Y4j+8i9DqYGyD5ePVgt4G0ICBX1bi1qNlylfxRg8Y3c1DFrRGyr0NpKQxSVXkYaVNvrCoudQIDAQAB
#    returnUrl: http://s9v2cw.natappfree.cc/alipay/return
#    notifyUrl: http://s9v2cw.natappfree.cc/alipay/notify
server:
 port: 8081
# port: 8088
spring:
 session:
  store-type: none
  #测试环境
#datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/colintest?useUnicode=true&characterEncoding=UTF-8
#      username: root 192.168.10.145
#      password: test@dev10224@@$
 #midpay环境
# datasource:
#ander环境
 datasource:
# #中转
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/colintest?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: test@dev10224@@$
 #真实
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.244.128.240:3306/shunfudb?useUnicode=true&characterEncoding=UTF-8
#ace
#    url: jdbc:mysql://47.52.77.234:3306/shunfudb?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://127.0.0.1:3306/shunfudb?useUnicode=true&characterEncoding=UTF-8
    username: shunfu
    password: colin123!@#
#    driver-class-name: com.mysql.jdbc.Driver
##    url: jdbc:mysql://127.0.0.1:3306/midpay?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://127.0.0.1:3306/colintest?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: test@dev10224@@$
#session存储格式为redis
 jpa:
   show-sql: false
   hibernate:
     ddl-auto: update
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 redis:
     host: 127.0.0.1
     port: 6379
     password:
     timeout: 5000
     pool:
       max-idle: 8
       min-idle: 0
       max-active: 8
       max-wait: -1

# redis:
#   database: 0

# redis:
#   database: 0
# redis:
#   database: 0

#   host: 192.168.11.128
#   password:
#   port: 6379
#
#jedis :
#  pool:
#      host : 192.168.11.128
#      port : 6379
#      config :
#        maxTotal: 100
#        maxIdle: 10
#        maxWaitMillis : 100000
 #  pool:
#     max-idle: 300wechat
#     min-idle: 100
#     max-active: 600
#     max-wait: 1000
#   sentinel:
#     master:
#     nodes:
#redis

#logging:
#  file: debug.log
#  pattern:
#    console: {yyyy}
#  level: debug
#management:
#  port: 54001
#  security:
#    enabled: false
#  health:
#    mail:
#      enabled: false
info:
  contact:
    email: xixicat@gmail.com
    phone: 0755-82890987
